// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Package.proto

package org.hyr.hfs.protobuf;

public interface PackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.hyr.hfs.protobuf.Package)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *metric数据
   * </pre>
   *
   * <code>repeated .org.hyr.hfs.protobuf.Record records = 1;</code>
   */
  java.util.List<org.hyr.hfs.protobuf.Record> 
      getRecordsList();
  /**
   * <pre>
   *metric数据
   * </pre>
   *
   * <code>repeated .org.hyr.hfs.protobuf.Record records = 1;</code>
   */
  org.hyr.hfs.protobuf.Record getRecords(int index);
  /**
   * <pre>
   *metric数据
   * </pre>
   *
   * <code>repeated .org.hyr.hfs.protobuf.Record records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <pre>
   *metric数据
   * </pre>
   *
   * <code>repeated .org.hyr.hfs.protobuf.Record records = 1;</code>
   */
  java.util.List<? extends org.hyr.hfs.protobuf.RecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <pre>
   *metric数据
   * </pre>
   *
   * <code>repeated .org.hyr.hfs.protobuf.Record records = 1;</code>
   */
  org.hyr.hfs.protobuf.RecordOrBuilder getRecordsOrBuilder(
      int index);

  /**
   * <pre>
   *数据时间戳
   * </pre>
   *
   * <code>uint64 timestamp = 2;</code>
   */
  long getTimestamp();

  /**
   * <pre>
   *该事件节点总包数
   * </pre>
   *
   * <code>uint32 total = 3;</code>
   */
  int getTotal();

  /**
   * <pre>
   *该数据包的索引index
   * </pre>
   *
   * <code>uint32 index = 4;</code>
   */
  int getIndex();
}
