// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Package.proto

package org.hyr.hfs.protobuf;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.hyr.hfs.protobuf.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *内容
   * </pre>
   *
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
